environment = "local"
namespace = "monitoring"
postgres_password = "testpassword"
kube_config_path  = "~/.kube/config"
api_url = "http://localhost:8092"
image_registry = ""
gitlab_ci_token = "placeholder"
