server:
  port: 8092
spring:
  application:
    name: management-api
  datasource:
    url: jdbc:postgresql://postgres-dev.monitoring.svc.cluster.local:5432/postgres
    username: postgres
    password: testpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  thymeleaf:
    suffix: .txt
    mode: TEXT
springdoc:
  swagger-ui:
    path: /swagger-ui.html
deployment:
  prometheus:
    config-url: http://prometheus-api-dev.monitoring.svc.cluster.local:8093/config
  grafana:
    config-url: http://grafana-api-dev.monitoring.svc.cluster.local:8094/config
  otel-collector:
    config-url: http://otel-collector-api-dev.monitoring.svc.cluster.local:8095/config
